### ISSUE TITLE
crouching on high block + movement checks

### ISSUE THREAD

**Issue by DanielW231** [KarmaAC/Issue-Tracker#114]
**Minecraft Version & Client**
1.8.8 - no client

**Check [What check should trigger if bypass] [What check is triggered if bug]*
Fly B1
Fly B2
NoFall
Can trigger Glide
Can trigger Spider

**Description**
Caused a lot of checks to occur just by shifting on edge of high block

**To Reproduce**
Shift on edge of high block lol

**Was the server lagging? - Was your ping high? - Were there any other factors different from normal gameplay?**
Ping ~200-300

**Video of the event**
https://gyazo.com/dd769bc5326512ca4c7788eb716bd235

**Additional context**
Add any other context or information you can give us

**Comment by thedarthonian** [comment]
This issue will persist until we add ping compensation to checks, which won't happen until the PingSpoof check has been created.
